# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf8cf8663e3dc2efc9b071c29dfc4b99df4f7fa98006254f797907f7b4c0b2c763d07cf893cd64fcd2a8554726ca9f115860ac4384f4f7cc9502df7c526a16e2

test:
  secret_key_base: e3dcdd0997501fbda0bdc3b8480f9236013c7ca2b7b3e7dd180a357b24b051c57891293e656662d57c52e6e5d66113063ca6ea3925cdfb4acf79efc5de7981f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
